### ISSUE TITLE
Label for Pressure graph needs to be changed

### ISSUE THREAD

**Issue by hemantkamalakar** [CentriaUniversityOfAppliedSciences/Android_RuuvitagScannner#2]
Hello, 
First of all thanks a lot for the RuuvitagScannner Android application.
I am using centriaruuvitagscanner_v2_beta_160717.apk and found that the label needs to be changed for the Pressure graph.
Currently it is showing 'Humidity' for Pressure.
![screenshot_2017-07-19-14-13-02-742_tki centria ruuviscanner](https://user-images.githubusercontent.com/1947238/28358712-7457c96e-6c8d-11e7-9633-85866813960e.png)

**Comment by jariisohanni** [comment]
Thanks for feedback, we are working with totally new graph system. This one was only a test. Stay tuned once update comes out.
